<a href="https://colab.research.google.com/github/pareshrnayak/ml-dl-daily/blob/main/%5B4%5D_vector_%26_matrix_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Vector & Matrix Operations (NumPy)**

In [1]:
import numpy as np

In [3]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print("v1:", v1)
print("v2:", v2)

v1: [1 2 3]
v2: [4 5 6]


In [4]:
#------Vector Addition-----

v_add = v1 + v2
print("vector addition:", v_add)

vector addition: [5 7 9]


In [5]:
#------Vector Substraction-----

v_sub = v2 - v1
print("vector substraction:", v_sub)

vector substraction: [3 3 3]


In [8]:
#----Scalar Multiplication----

v_scalar = 3 * v1
print("Scalar Multiplication:", v_scalar)

#In this 3 is a scalar and v1 is vector. But scalar can be any number.

Scalar Multiplication: [3 6 9]


In [9]:
#----Dot Product----

dot_product = np.dot(v1, v2)
print("Dot Product:", dot_product)

Dot Product: 32


In [10]:
#------Create Matrices-----

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]


In [11]:
#----Matrix Addition----

A_plus_B = A + B
print("Matrix Addition:\n", A_plus_B)

Matrix Addition:
 [[ 6  8]
 [10 12]]


In [12]:
A_mul_B = np.dot(A, B)
print("Matrix Multiplication:\n", A_mul_B)

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [13]:
A_T = A.T
print("Transpose of A:\n", A_T)

Transpose of A:
 [[1 3]
 [2 4]]


In [14]:
print("Shape of v1:", v1.shape)
print("Shape of A:", A.shape)

Shape of v1: (3,)
Shape of A: (2, 2)


# Vector & Matrix Operations (Machine Learning Foundations)

In Machine Learning and Deep Learning, **everything is represented using numbers**.  
Vectors and matrices are structured ways to organize these numbers so that computers can
process data efficiently and learn patterns.

Without vectors and matrices, **ML and DL cannot exist**.

---

## 1️⃣ Vectors

A **vector** is a **one-dimensional list of numbers**.

Example:
[1, 2, 3]


In Machine Learning:
- Each number represents a **feature**
- One vector represents **one data sample**
- Model weights and gradients are also vectors

---

## 2️⃣ Vector Operations

### 🔹 Vector Addition & Subtraction

Vectors are added or subtracted **element by element**.

Why this matters:
- Used to update model parameters
- Used in gradient descent

Example idea:
new_weights = old_weights + correction


---

### 🔹 Scalar Multiplication

A **scalar** is a **single number**.

Scalar multiplication means multiplying **every value in a vector** by one number.

Formula:
$$
k \cdot \vec{v}
$$

Example:
3 × [1, 2, 3] = [3, 6, 9]


Important:
- The scalar can be **any number** (single digit, double digit, decimal, negative)
- Used to control learning speed and scale data

Why needed in ML:
- Learning rate × gradient
- Feature scaling
- Weight adjustment

---

### 🔹 Dot Product (Very Important)

The dot product converts **two vectors into one number**.

Formula:
$$
\vec{a} \cdot \vec{b} = \sum a_i b_i
$$

Meaning:
> It measures how strongly two vectors are related.

In ML:
- Features · Weights → Prediction
- Used in linear regression and neural networks

---

## 3️⃣ Matrices

A **matrix** is a **two-dimensional table of numbers**.

Example:
[[1, 2],
[3, 4]]


In ML:
- Rows → data samples
- Columns → features
- Entire datasets are stored as matrices

---

## 4️⃣ Matrix Operations

### 🔹 Matrix Addition

Matrices are added **element by element**.

Why needed:
- Bias addition
- Batch processing

---

### 🔹 Matrix Multiplication (Core of Deep Learning)

Matrix multiplication combines rows of one matrix with columns of another.

Formula:
$$
C = A \times B
$$

Why extremely important:
- Neural network forward pass
- Layer-to-layer data flow
- Feature transformation

> Every deep learning model is built on matrix multiplication.

---

### 🔹 Transpose of a Matrix

Transpose swaps rows and columns.

Formula:
$$
A^T
$$

Why needed:
- Shape alignment
- Gradient calculations
- Mathematical correctness

---

## 5️⃣ Shape & Broadcasting

### 🔹 Shape

Shape tells how many **rows and columns** an array has.

Why important:
- Wrong shape causes errors
- ML models expect specific dimensions

---

### 🔹 Broadcasting

Broadcasting allows NumPy to automatically apply operations
between arrays of different shapes.

Why useful:
- Cleaner code
- Faster computation
- No manual loops

---

## 6️⃣ ML Intuition

- **Vectors** → features, weights, gradients
- **Matrices** → datasets, layers
- **Dot product & matrix multiplication** → predictions

Without these operations, **ML models cannot learn**.

---

## ✅ Key Takeaway

- Vectors and matrices are the **language of Machine Learning**
- Scalar multiplication scales learning
- Dot product generates predictions
- Matrix multiplication powers neural networks

Mastering these basics is essential before moving to ML and DL algorithms.